### ISSUE TITLE
RS训练分类模型，导出之后，预测报错

### ISSUE THREAD

**Issue by L-xiaolu** [PaddleCV-SIG/PaddleRS#104]
利用RS 训练了HRNet_W18_C模型，模型训练、导出都正常，就是用导出的模型做预测的时候出现了错误。
Traceback (most recent call last):
  File "demo.py", line 52, in <module>
    result = predictor.predict(img_file=img1,transforms=eval_transforms)
  File "/home/aistudio/PaddleRS/paddlers/deploy/predictor.py", line 279, in predict
    results = self._run(images=images, topk=topk, transforms=transforms)
  File "/home/aistudio/PaddleRS/paddlers/deploy/predictor.py", line 235, in _run
    transforms=transforms)
  File "/home/aistudio/PaddleRS/paddlers/deploy/predictor.py", line 175, in postprocess
    preds = self._model._postprocess(net_outputs, true_topk)
TypeError: 'NoneType' object is not callable
![image](https://user-images.githubusercontent.com/77192830/174521468-7ccc781e-81bc-4999-a449-fc8cc22288e0.png)
请问这个错误怎么处理

**Comment by Bobholamovic** [comment]
您好，这是一个bug。目前修复此bug的PR正在review中，请耐心等待。修复完成后我们会通知您，届时请您拉取最新的代码以解决此问题。

#105

**Comment by L-xiaolu** [comment]
> 您好，这是一个bug。目前修复此bug的PR正在review中，请耐心等待。修复完成后我们会通知您，届时请您拉取最新的代码以解决此问题。
> 
> #105

好的，感谢您的工作

**Comment by Bobholamovic** [comment]
bug已修复，请您拉取最新代码再次尝试。如果问题得到解决，麻烦关闭这个issue。

**Comment by L-xiaolu** [comment]
好的，哥
